name: Example Tests
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: init
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: install
        working-directory: .
        run: npm install --force
      - name: test
        working-directory: .
        run: npm run test
        env:
          SPHERE_LOG_LEVEL: 'debug'
          SPHERE_API_KEY: '7a48a924-5bc1-4111-b684-124307ee91f5'
          SOLANA_PRIVATE_KEY: '2uxtduD2Ck3KhGugrS13GXwrEmvCTWEtoAbWrann7frdcjuTDQKuZmnLi9HN2txJ17obSYLya4WChgp9GnCzxAN9'
          SOLANA_RPC_URL: 'https://solana-devnet.g.alchemy.com/v2/g7_hoh1SBqVkHqEQoGmx2xo5Yj0Wt7Lh'
